### ISSUE TITLE
v2.2.0 is released, but list of significant changes ends at 1.2

### ISSUE THREAD

**Issue by naugtur** [alexfernandez/loadtest#125]
I assume a major version bump was required for a reason. What's new?

**Comment by alexfernandez** [comment]
There have been many significant changes. Rather than list them all, I have removed the change log altogether. You can simply browse them [here](https://github.com/alexfernandez/loadtest/commits/master), which I think is more convenient for everyone: I don't forget changes, and you can see them with all the detail.

**Comment by naugtur** [comment]
Makes sense.
Thanks for all the work you put in!
