### ISSUE TITLE
actual number of requests is reported wrongly when using concurrency

### ISSUE THREAD

**Issue by pkgulati** [alexfernandez/loadtest#130]
Although it is documented that actual number of requests may be more than what is given in options (input), however at least in results reported (output) the actual number of requests must be shown properly.

**Comment by alexfernandez** [comment]
What do you suggest? Care to propose a pull request?

**Comment by pkgulati** [comment]
Yes I can do that. I have one doubt. Currently the check against maxRequests is being done on each request completion, why we can not move the check to request initiation (makeRequest).

**Comment by alexfernandez** [comment]
That is a good idea! :+1:

**Comment by vKongv** [comment]
Anyone is working on this? It create way more requests then we thought...

**Comment by alexfernandez** [comment]
Not that I know of, but PRs are always welcome!

**Comment by pwmcintyre** [comment]
FYI - I was able to get a reliable request cound using the following loadtest options:

```TypeScript
    let requests = 0
    const options: loadtest.LoadTestOptions = {
        ...
        statusCallback: (error, result, latency) => {
            requests++
        },
    }
```

**Comment by AlexShkunov** [comment]
Resolution is still planned for this, @alexfernandez as the package creator would it be the easiest for you to fix?

**Comment by alexfernandez** [comment]
I am afraid I don't have the bandwidth to look into it right now, and frankly it has not been an issue for me so far, but I'm willing to review and merge any PRs that any of you propose.

**Comment by alexfernandez** [comment]
Thanks to @charlieknoll we have a fix in loadtest@3.0.9, please verify.

**Comment by CreativeCactus** [comment]
It is unclear if this issue is still open.
The [commit in question](https://github.com/alexfernandez/loadtest/commit/09ce8ef830213d6b456612b1eaea4c88ba05b158] doesn't explain how to access the `completedRequests`, (I have made a PR for TS users, [here](https://github.com/alexfernandez/loadtest/pull/191)).

The value still appears to be incorrect. For users who find this thread in the future, there currently appears to be no way of getting the exact number of requests, either by setting a max or by getting the count from `loadtest`.

**Comment by alexfernandez** [comment]
Closing, please reopen if needed.
