### ISSUE TITLE
Protocol "https:" not supported.

### ISSUE THREAD

**Issue by AdrienFromToulouse** [alexfernandez/loadtest#69]
I got this error. However the doc is telling the opposite.

**Comment by alexfernandez** [comment]
Are you sure that this error is not coming from the destination web server? Can you paste the complete trace? Thanks!

**Comment by chocochik92** [comment]
I get this same issue when using `-k`

**Comment by alexfernandez** [comment]
@chocochik92 So you don't get it _without_ `-k`?

**Comment by chocochik92** [comment]
correct

**Comment by alexfernandez** [comment]
OK, I think I found it. The previous version of [agentkeepalive](https://github.com/node-modules/agentkeepalive) said:

```
node >= 0.11.0: use agentkeepalive@1.2.0+
node < 0.11.0: use agentkeepalive@0.2.2
```
I think that the new 2.x should support both versions, and also recover support for HTTPS. Can either of you test it changing the dep in `package.json` and report back? Or, even better, send a PR? Otherwise I will do it myself, but it may take a little bit longer. Thanks!

**Comment by chocochik92** [comment]
change the node dependency to 0.11.0?

**Comment by alexfernandez** [comment]
It should not be needed, and besides many people are still using 0.10
(myself included).

**Comment by alexfernandez** [comment]
Please try version 1.2.12, it should solve this issue. Please reopen if not so.
