### ISSUE TITLE
Allow execution in non-quiet mode with a callback

### ISSUE THREAD

**Issue by ozomer** [alexfernandez/loadtest#98]
[loadtest.js line 365](https://github.com/alexfernandez/loadtest/blob/master/lib/loadtest.js#L365) should change from `if (callback)` to `if (callback && !("quiet" in options))`

**Comment by alexfernandez** [comment]
The current behavior is that `quiet` is enabled always if a callback is passed, since in that case you will probably want to embed loadtest in your own code.

I am more inclined to make it explicit in the documentation (it is already in the [comment](https://github.com/alexfernandez/loadtest/blob/master/lib/loadtest.js#L333). What is your use case to want both log and callback? Pull requests are welcome, by the way :)

**Comment by ozomer** [comment]
The log prints are great. I just wanted to be able to tell when the test has finished (via the callback) so I could run some code after.
Right now I am creating an interval that checks `operation.running`... a really ugly solution...

**Comment by alexfernandez** [comment]
OK, that is clear. Do you want to submit a pull request so I can merge it?

**Comment by ozomer** [comment]
Nah, it's just one line to fix. You can change it yourself, I don't care about the credit.

**Comment by alexfernandez** [comment]
OK, fixed in https://github.com/alexfernandez/loadtest/commit/a01e8c344333eafce11dcc326bb2ff811d3ecd72, and published in 1.3.5. Thanks!
